yearly:
  folder: 'solutions/SAPP-yearly-emissions-10flex-0.2-v3-old'
  extra: '-old'
monthly:
  folder: 'solutions/SAPP-monthly-emissions-10flex-0.2-v3'
  extra: ''
weekly:
  folder: 'solutions/SAPP-weekly-emissions-10flex-0.2-v3+2-ok-convergence100'
  extra: '+2-ok-convergence100'
centralized:
  network_path: "./pypsa_earth_before_weekly_rerun/results/SAPP-centralized-2h-120flex-363mt/networks/elec_s_120flex_ec_lcopt_Co2L-2H.nc"
countries:
    - AO
    - BW
    - CD
    - LS
    - MW
    - MZ
    - NA
    - SZ
    - TZ
    - ZA
    - ZM
    - ZW
